### ISSUE TITLE
Errors in log on HA 0.80.1

### ISSUE THREAD

**Issue by gerard33** [matisaul/vertical-style-card#1]
Thanks for this awesome card!

In HA 0.80.1 I have the following errors in the console log. In the version before, also 0.80, this card was working fine.

```
Uncaught TypeError: Cannot read property 'childNodes' of null
    at _refCards.forEach (vertical-style-card.js?v=0.0.2:73)
    at Array.forEach (<anonymous>)
    at HTMLElement.connectedCallback (vertical-style-card.js?v=0.0.2:66)
    at elements.forEach.el (f8d29840aefd30333667.chunk.js:1590)
    at Array.forEach (<anonymous>)
    at HTMLElement._createCards (f8d29840aefd30333667.chunk.js:1590)
    at Object.runMethodEffect [as fn] (app-7466319f.js:1067)
    at runEffectsForProperty (app-7466319f.js:1067)
    at runEffects (app-7466319f.js:1067)
    at HTMLElement._propertiesChanged (app-7466319f.js:1067)
```

Any ideas how to fix this?

**Comment by codylv7** [comment]
Same issue here

**Comment by matisaul** [comment]
> Thanks for this awesome card!
> 
> In HA 0.80.1 I have the following errors in the console log. In the version before, also 0.80, this card was working fine.
> 
> ```
> Uncaught TypeError: Cannot read property 'childNodes' of null
>     at _refCards.forEach (vertical-style-card.js?v=0.0.2:73)
>     at Array.forEach (<anonymous>)
>     at HTMLElement.connectedCallback (vertical-style-card.js?v=0.0.2:66)
>     at elements.forEach.el (f8d29840aefd30333667.chunk.js:1590)
>     at Array.forEach (<anonymous>)
>     at HTMLElement._createCards (f8d29840aefd30333667.chunk.js:1590)
>     at Object.runMethodEffect [as fn] (app-7466319f.js:1067)
>     at runEffectsForProperty (app-7466319f.js:1067)
>     at runEffects (app-7466319f.js:1067)
>     at HTMLElement._propertiesChanged (app-7466319f.js:1067)
> ```
> Any ideas how to fix this?

Could you share your ui-lovelace.yaml? I'm not getting errors in 0.80.2

**Comment by gerard33** [comment]
@matisaul 
It's indeed only happening when the card is inside a `vertical-stack`.

```yaml
- type: vertical-stack
  cards:
    - type: custom:vertical-style-card #vertical-stack-in-card
      # title: Afvalinzameling
      style:
        # font_size: 18px
        # font-weight: bold
        border: false
        background_color: var(--paper-card-background-color)
      cards:
        - type: picture-elements
          image: /local/pictures/vuilnis.png
          title: Afvalinzameling
          elements:
            - type: custom:text-element
              text: "Morgen"
              style:
                top: 5%
                left: 10%
                color: 'var(--primary-text-color)'
            - type: state-label
              entity: sensor.trash_tomorrow
              style:
                top: 15%
                left: 10%
                color: 'var(--accent-color)'
            - type: custom:text-element
              text: "Papier"
              style:
                top: 5%
                left: 30%
                color: 'var(--primary-text-color)'
            - type: state-label
              entity: sensor.papier_next
              style:
                top: 15%
                left: 30%
                color: 'var(--accent-color)'
            - type: custom:text-element
              text: "GFT"
              style:
                top: 5%
                left: 50%
                color: 'var(--primary-text-color)'
            - type: state-label
              entity: sensor.gft_next
              style:
                top: 15%
                left: 50%
                color: 'var(--accent-color)'
            - type: custom:text-element
              text: "Restafval"
              style:
                top: 5%
                left: 70%
                color: 'var(--primary-text-color)'
            - type: state-label
              entity: sensor.rest_next
              style:
                top: 15%
                left: 70%
                color: 'var(--accent-color)'
            - type: custom:text-element
              text: "Plastic"
              style:
                top: 5%
                left: 90%
                color: 'var(--primary-text-color)'
            - type: state-label
              entity: sensor.plasticplus_next
              style:
                top: 15%
                left: 90%
                color: 'var(--accent-color)'
        - type: glance
          column_width: 50%
          entities:
            - sensor.trash_today
            - input_boolean.notify_trash
```
![screenshot_4](https://user-images.githubusercontent.com/11230573/47683193-2b8a5780-dbcf-11e8-8975-2daa5436ecda.jpg)
