### ISSUE TITLE
Layout issue with custom:button-card

### ISSUE THREAD

**Issue by jarrah31** [matisaul/vertical-style-card#2]
Hi - this card would be just what I need to group buttons into named sections, but it seems to mess up the button layout...

HA - 0.81.5
button-card - 0.1.3

Yaml used:
```
  - title: test
    icon: mdi:run
    panel: false
    id: motion
    cards:
      - type: custom:vertical-style-card
        title: Motion
        cards:
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: binary_sensor.motion_study
                color_type: label-card
                color: rgb(255,69,0)
                color_off: rgb(50,205,50)
                name: "Study"
                icon: mdi:run
                size: 20%
                style:
                  - text-transform: none
etc
```
View with custom:vertical-style-card applied:
![image](https://user-images.githubusercontent.com/3072303/48376194-12e76a80-e6c2-11e8-9e48-09b7c786f447.png)

View without:
![image](https://user-images.githubusercontent.com/3072303/48376245-46c29000-e6c2-11e8-8d19-fcb868a257bf.png)

Using:
```
  - title: test
    icon: mdi:run
    panel: false
    id: motion
    cards:
      - type: vertical-stack
        # title: Motion
        cards:
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                entity: binary_sensor.motion_study
                color_type: label-card
                color: rgb(255,69,0)
                color_off: rgb(50,205,50)
                name: "Study"
                icon: mdi:run
                size: 20%
                style:
                  - text-transform: none
```
Thanks!
