### ISSUE TITLE
Button padding issue when using Custom:UI Tiles Lovelace Card

### ISSUE THREAD

**Issue by jarrah31** [matisaul/vertical-style-card#3]
Hope you don’t mind but I’ve come across a similar situation with the new Lovelace version of Custom UI: Tiles found below, and I wondered if you could have a look please?

https://github.com/rodrigofragadf/lovelace-cards/tree/master/tiles-card 

With `custom:vertical-style-card:`
![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/b/4/b4522dc48d9220f1069543dd2f773e6730101cee.png)

With `vertical-stack`
![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/3/e/3e589683b21733eb597f2905414fcc7c8592280d.png)

The yaml code is as follows:
```
  - title: test
    icon: mdi:run
    panel: false
    path: test
    cards:
      - type: vertical-stack
      # - type: custom:vertical-style-card
        cards:
          - type: custom:tiles-card
            card_settings:
              title: test
              gap: 10px
              padding: 0px
              columns: 5
              row_height: 45px
              templates:
                style: "return 'box-shadow: 0px 0px;'"
            entities:
              - entity: light.kitchen
                row: 1
              - entity: light.kitchen
                row: 1
              - entity: light.kitchen
                row: 1
              - entity: light.kitchen
                row: 1
              - entity: light.kitchen
                row: 1
          - type: custom:tiles-card
            card_settings:
              display: hidden
              gap: 10px
              padding: 0px
              columns: 1
              row_height: 15px
            entities:
              - entity: light.kitchen
                display: hidden
          - type: custom:tiles-card
            card_settings:
              display: hidden
              gap: 10px
              padding: 0px
              columns: 3
              row_height: 45px
            entities:
              - entity: light.kitchen
                row: 1
              - entity: light.kitchen
                row: 1
              - entity: light.kitchen
                row: 1
          - type: custom:tiles-card
            card_settings:
              display: hidden
              gap: 10px
              padding: 0px
              columns: 2
              row_height: 45px
            entities:
              - entity: light.kitchen
                row: 1
              - entity: light.kitchen
                row: 1
```
Thank you!
