### ISSUE TITLE
element.setConfig is not a function

### ISSUE THREAD

**Issue by kirbyschapman** [matisaul/vertical-style-card#7]
I narrowed this error down to the vertical style card. I use this as the outside wrapper with a number of custom:button-cards in a horizontal stack inside. A snippet of the code is:
```
      - cards:
          - type: 'custom:button-card'
            color_type: label-card
            name: Test Stuff
            color: 'rgb(44, 109, 214)'
          - cards:
              - <<: *labelbinarysensor
                entity: binary_sensor.sleeping_baye
                color_type: card
                styles:
                  card:
                    - margin: 2px 2px 2px 0px
                label: >
                 [[[  return 'Sleeping Baye';  ]]]
              - <<: *labelbinarysensor
                entity: binary_sensor.all_rokus_not_playing
                color_type: card
                label: >
                 [[[  return 'Rokus Not Playing';  ]]]
              - <<: *labelbinarysensor
                entity: binary_sensor.extended_away
                color_type: card
                label: >
                 [[[  return 'Extended Away';  ]]]
            type: horizontal-stack
          - type: 'custom:button-card'
            color_type: label-card
            name: HVAC Actions
            color: 'rgb(44, 109, 214)'
          - cards:
              - <<: *ib_card_turn_on
                entity: input_boolean.put_house_hvac_in_dr_saver_2nd_sleep_mode
                name: Sleep!
              - <<: *ib_card_turn_on
                entity: input_boolean.put_house_hvac_dr_comfort_2nd_saver
                name: 1-comfort 2-saver
              - <<: *ib_card_turn_on
                entity: input_boolean.put_house_hvac_dr_saver_2nd_comfort
                name: 1-saver 2-comfort
            type: horizontal-stack
        panel: false
        type: 'custom:vertical-style-card'
```
The anchors are:
```
  hvac_binary_sensor_card: &labelbinarysensor
    color_type: icon
    show_entity_picture: false
    show_icon: true
    show_name: false
    show_state: false
    show_label: true
    show_units: false
    show_last_changed: false
    template: binary_sensor_format
    state:
      - color: 'rgb(0, 102, 204)'
        value: 'off'
        icon: 'mdi:checkbox-blank-circle-outline'
      - color: 'rgb(255, 153, 51)'
        value: 'on'
        icon: 'mdi:circle-slice-8'
        styles:
          icon:
            - animation: blink 2s ease infinite
    hold_action:
      action: more-info
    tap_action:
      action: more-info
    type: 'custom:button-card'
  input_boolean_card: &ib_card_turn_on
    color_type: icon
    show_entity_picture: false
    show_icon: true
    show_name: true
    show_state: false
    show_label: false
    show_units: false
    show_last_changed: false
    template: name_label
    state:
      - color: 'rgb(0, 102, 204)'
        value: 'off'
        icon: 'mdi:toggle-switch-off'
      - color: 'rgb(255, 153, 51)'
        value: 'on'
        icon: 'mdi:toggle-switch'
    hold_action:
      action: more-info
    tap_action:
      action: call-service
      service: input_boolean.turn_on
      service_data:
        entity_id: entity
    type: 'custom:button-card'

```

I have the same buttons in a second card on the same screen, but use the vertical-stack UI card, and that renders fine. I can reproduce this by clearing the cache, and then refreshing the screen. It does this on my Win 10 Chrome and Android Chrome. 

Is this a race condition between the button-card and vertical-style-card loading? If I then use the lovelace Refresh method, it renders. 

I am using the latest version (0.1.1) of the vertical-style-card.
